services:
  infrastructure:
    container_name: infrastructure
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      # This is called when Localstack container is starting up.
      # Using this for AWS CLI commands currently.
      - ./init-scripts/init-localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
      - ./init-scripts/sqs-topic-definition.json:/opt/code/localstack/sqs-topic-definition.json

  app:
    depends_on:
      - infrastructure
    container_name: app
    build: # "context" and "dockerfile" fields have to be under "build"
      context: ../
      dockerfile: app/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev